# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    username: root
    password: Mateobeccan2002

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: NjNjMjkxOWZmNzVlNjI0MmEyNzEyYmIxYTE1ZjQxMzlkOWIxZjkwYWJmMTEyZDhlOWQ1MzgxNmRmN2EyZDZiZThmZjRmODBjYjBkMTU5ZTA1ZjY3MzUwNmFkOWE0OWY1NjA1N2Q2ZjgzNjM5YWM0NmRhZmE2Mjk4MWE3ZWFkYzc=
