package com.mycompany.hospital.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AntecedenteClinicoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAntecedenteClinicoAllPropertiesEquals(AntecedenteClinico expected, AntecedenteClinico actual) {
        assertAntecedenteClinicoAutoGeneratedPropertiesEquals(expected, actual);
        assertAntecedenteClinicoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAntecedenteClinicoAllUpdatablePropertiesEquals(AntecedenteClinico expected, AntecedenteClinico actual) {
        assertAntecedenteClinicoUpdatableFieldsEquals(expected, actual);
        assertAntecedenteClinicoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAntecedenteClinicoAutoGeneratedPropertiesEquals(AntecedenteClinico expected, AntecedenteClinico actual) {
        assertThat(actual)
            .as("Verify AntecedenteClinico auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAntecedenteClinicoUpdatableFieldsEquals(AntecedenteClinico expected, AntecedenteClinico actual) {
        assertThat(actual)
            .as("Verify AntecedenteClinico relevant properties")
            .satisfies(a -> assertThat(a.getTitulo()).as("check titulo").isEqualTo(expected.getTitulo()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()))
            .satisfies(a -> assertThat(a.getFechaRegistro()).as("check fechaRegistro").isEqualTo(expected.getFechaRegistro()))
            .satisfies(a -> assertThat(a.getObservaciones()).as("check observaciones").isEqualTo(expected.getObservaciones()))
            .satisfies(a -> assertThat(a.getActivo()).as("check activo").isEqualTo(expected.getActivo()))
            .satisfies(a -> assertThat(a.getFechaAlta()).as("check fechaAlta").isEqualTo(expected.getFechaAlta()))
            .satisfies(a -> assertThat(a.getFechaBaja()).as("check fechaBaja").isEqualTo(expected.getFechaBaja()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAntecedenteClinicoUpdatableRelationshipsEquals(AntecedenteClinico expected, AntecedenteClinico actual) {
        assertThat(actual)
            .as("Verify AntecedenteClinico relationships")
            .satisfies(a -> assertThat(a.getHistoriaClinica()).as("check historiaClinica").isEqualTo(expected.getHistoriaClinica()));
    }
}
