package com.mycompany.hospital.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CiudadAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCiudadAllPropertiesEquals(Ciudad expected, Ciudad actual) {
        assertCiudadAutoGeneratedPropertiesEquals(expected, actual);
        assertCiudadAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCiudadAllUpdatablePropertiesEquals(Ciudad expected, Ciudad actual) {
        assertCiudadUpdatableFieldsEquals(expected, actual);
        assertCiudadUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCiudadAutoGeneratedPropertiesEquals(Ciudad expected, Ciudad actual) {
        assertThat(actual)
            .as("Verify Ciudad auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCiudadUpdatableFieldsEquals(Ciudad expected, Ciudad actual) {
        assertThat(actual)
            .as("Verify Ciudad relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getCodigo()).as("check codigo").isEqualTo(expected.getCodigo()))
            .satisfies(a -> assertThat(a.getCodigoPostal()).as("check codigoPostal").isEqualTo(expected.getCodigoPostal()))
            .satisfies(a -> assertThat(a.getFechaAlta()).as("check fechaAlta").isEqualTo(expected.getFechaAlta()))
            .satisfies(a -> assertThat(a.getFechaBaja()).as("check fechaBaja").isEqualTo(expected.getFechaBaja()))
            .satisfies(a -> assertThat(a.getActivo()).as("check activo").isEqualTo(expected.getActivo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCiudadUpdatableRelationshipsEquals(Ciudad expected, Ciudad actual) {
        assertThat(actual)
            .as("Verify Ciudad relationships")
            .satisfies(a -> assertThat(a.getProvincia()).as("check provincia").isEqualTo(expected.getProvincia()));
    }
}
