package com.mycompany.hospital.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ConsultaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConsultaAllPropertiesEquals(Consulta expected, Consulta actual) {
        assertConsultaAutoGeneratedPropertiesEquals(expected, actual);
        assertConsultaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConsultaAllUpdatablePropertiesEquals(Consulta expected, Consulta actual) {
        assertConsultaUpdatableFieldsEquals(expected, actual);
        assertConsultaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConsultaAutoGeneratedPropertiesEquals(Consulta expected, Consulta actual) {
        assertThat(actual)
            .as("Verify Consulta auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConsultaUpdatableFieldsEquals(Consulta expected, Consulta actual) {
        assertThat(actual)
            .as("Verify Consulta relevant properties")
            .satisfies(a -> assertThat(a.getCodigo()).as("check codigo").isEqualTo(expected.getCodigo()))
            .satisfies(a -> assertThat(a.getFechaHoraInicio()).as("check fechaHoraInicio").isEqualTo(expected.getFechaHoraInicio()))
            .satisfies(a -> assertThat(a.getFechaHoraFin()).as("check fechaHoraFin").isEqualTo(expected.getFechaHoraFin()))
            .satisfies(a -> assertThat(a.getSintomas()).as("check sintomas").isEqualTo(expected.getSintomas()))
            .satisfies(a -> assertThat(a.getMotivoConsulta()).as("check motivoConsulta").isEqualTo(expected.getMotivoConsulta()))
            .satisfies(a -> assertThat(a.getExamenFisico()).as("check examenFisico").isEqualTo(expected.getExamenFisico()))
            .satisfies(a -> assertThat(a.getObservaciones()).as("check observaciones").isEqualTo(expected.getObservaciones()))
            .satisfies(a -> assertThat(a.getIndicaciones()).as("check indicaciones").isEqualTo(expected.getIndicaciones()))
            .satisfies(a -> assertThat(a.getActiva()).as("check activa").isEqualTo(expected.getActiva()))
            .satisfies(a -> assertThat(a.getFechaAlta()).as("check fechaAlta").isEqualTo(expected.getFechaAlta()))
            .satisfies(a -> assertThat(a.getFechaBaja()).as("check fechaBaja").isEqualTo(expected.getFechaBaja()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConsultaUpdatableRelationshipsEquals(Consulta expected, Consulta actual) {
        assertThat(actual)
            .as("Verify Consulta relationships")
            .satisfies(a -> assertThat(a.getTurno()).as("check turno").isEqualTo(expected.getTurno()))
            .satisfies(a -> assertThat(a.getPaciente()).as("check paciente").isEqualTo(expected.getPaciente()))
            .satisfies(a -> assertThat(a.getMedico()).as("check medico").isEqualTo(expected.getMedico()))
            .satisfies(a -> assertThat(a.getHistoriaClinica()).as("check historiaClinica").isEqualTo(expected.getHistoriaClinica()));
    }
}
