package com.mycompany.hospital.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ContactoEmergenciaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContactoEmergenciaAllPropertiesEquals(ContactoEmergencia expected, ContactoEmergencia actual) {
        assertContactoEmergenciaAutoGeneratedPropertiesEquals(expected, actual);
        assertContactoEmergenciaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContactoEmergenciaAllUpdatablePropertiesEquals(ContactoEmergencia expected, ContactoEmergencia actual) {
        assertContactoEmergenciaUpdatableFieldsEquals(expected, actual);
        assertContactoEmergenciaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContactoEmergenciaAutoGeneratedPropertiesEquals(ContactoEmergencia expected, ContactoEmergencia actual) {
        assertThat(actual)
            .as("Verify ContactoEmergencia auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContactoEmergenciaUpdatableFieldsEquals(ContactoEmergencia expected, ContactoEmergencia actual) {
        assertThat(actual)
            .as("Verify ContactoEmergencia relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getTelefono()).as("check telefono").isEqualTo(expected.getTelefono()))
            .satisfies(a -> assertThat(a.getParentesco()).as("check parentesco").isEqualTo(expected.getParentesco()))
            .satisfies(a -> assertThat(a.getObservaciones()).as("check observaciones").isEqualTo(expected.getObservaciones()))
            .satisfies(a -> assertThat(a.getPrioridad()).as("check prioridad").isEqualTo(expected.getPrioridad()))
            .satisfies(a -> assertThat(a.getActivo()).as("check activo").isEqualTo(expected.getActivo()))
            .satisfies(a -> assertThat(a.getFechaAlta()).as("check fechaAlta").isEqualTo(expected.getFechaAlta()))
            .satisfies(a -> assertThat(a.getFechaBaja()).as("check fechaBaja").isEqualTo(expected.getFechaBaja()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContactoEmergenciaUpdatableRelationshipsEquals(ContactoEmergencia expected, ContactoEmergencia actual) {
        assertThat(actual)
            .as("Verify ContactoEmergencia relationships")
            .satisfies(a -> assertThat(a.getPersona()).as("check persona").isEqualTo(expected.getPersona()));
    }
}
