package com.mycompany.hospital.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DiagnosticoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDiagnosticoAllPropertiesEquals(Diagnostico expected, Diagnostico actual) {
        assertDiagnosticoAutoGeneratedPropertiesEquals(expected, actual);
        assertDiagnosticoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDiagnosticoAllUpdatablePropertiesEquals(Diagnostico expected, Diagnostico actual) {
        assertDiagnosticoUpdatableFieldsEquals(expected, actual);
        assertDiagnosticoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDiagnosticoAutoGeneratedPropertiesEquals(Diagnostico expected, Diagnostico actual) {
        assertThat(actual)
            .as("Verify Diagnostico auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDiagnosticoUpdatableFieldsEquals(Diagnostico expected, Diagnostico actual) {
        assertThat(actual)
            .as("Verify Diagnostico relevant properties")
            .satisfies(a -> assertThat(a.getCodigo()).as("check codigo").isEqualTo(expected.getCodigo()))
            .satisfies(a -> assertThat(a.getFechaDiagnostico()).as("check fechaDiagnostico").isEqualTo(expected.getFechaDiagnostico()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()))
            .satisfies(a -> assertThat(a.getObservaciones()).as("check observaciones").isEqualTo(expected.getObservaciones()))
            .satisfies(a -> assertThat(a.getActivo()).as("check activo").isEqualTo(expected.getActivo()))
            .satisfies(a -> assertThat(a.getFechaResolucion()).as("check fechaResolucion").isEqualTo(expected.getFechaResolucion()))
            .satisfies(a -> assertThat(a.getEsPrincipal()).as("check esPrincipal").isEqualTo(expected.getEsPrincipal()))
            .satisfies(a -> assertThat(a.getFechaAlta()).as("check fechaAlta").isEqualTo(expected.getFechaAlta()))
            .satisfies(a -> assertThat(a.getFechaBaja()).as("check fechaBaja").isEqualTo(expected.getFechaBaja()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDiagnosticoUpdatableRelationshipsEquals(Diagnostico expected, Diagnostico actual) {
        assertThat(actual)
            .as("Verify Diagnostico relationships")
            .satisfies(a -> assertThat(a.getConsulta()).as("check consulta").isEqualTo(expected.getConsulta()))
            .satisfies(a -> assertThat(a.getPaciente()).as("check paciente").isEqualTo(expected.getPaciente()))
            .satisfies(a -> assertThat(a.getMedico()).as("check medico").isEqualTo(expected.getMedico()))
            .satisfies(a -> assertThat(a.getTipoDiagnostico()).as("check tipoDiagnostico").isEqualTo(expected.getTipoDiagnostico()))
            .satisfies(a -> assertThat(a.getEstadoDiagnostico()).as("check estadoDiagnostico").isEqualTo(expected.getEstadoDiagnostico()));
    }
}
