package com.mycompany.hospital.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EnfermeroAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEnfermeroAllPropertiesEquals(Enfermero expected, Enfermero actual) {
        assertEnfermeroAutoGeneratedPropertiesEquals(expected, actual);
        assertEnfermeroAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEnfermeroAllUpdatablePropertiesEquals(Enfermero expected, Enfermero actual) {
        assertEnfermeroUpdatableFieldsEquals(expected, actual);
        assertEnfermeroUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEnfermeroAutoGeneratedPropertiesEquals(Enfermero expected, Enfermero actual) {
        assertThat(actual)
            .as("Verify Enfermero auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEnfermeroUpdatableFieldsEquals(Enfermero expected, Enfermero actual) {
        assertThat(actual)
            .as("Verify Enfermero relevant properties")
            .satisfies(a -> assertThat(a.getMatricula()).as("check matricula").isEqualTo(expected.getMatricula()))
            .satisfies(a ->
                assertThat(a.getFechaMatriculacion()).as("check fechaMatriculacion").isEqualTo(expected.getFechaMatriculacion())
            )
            .satisfies(a -> assertThat(a.getActivo()).as("check activo").isEqualTo(expected.getActivo()))
            .satisfies(a -> assertThat(a.getFechaAlta()).as("check fechaAlta").isEqualTo(expected.getFechaAlta()))
            .satisfies(a -> assertThat(a.getFechaBaja()).as("check fechaBaja").isEqualTo(expected.getFechaBaja()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEnfermeroUpdatableRelationshipsEquals(Enfermero expected, Enfermero actual) {
        assertThat(actual)
            .as("Verify Enfermero relationships")
            .satisfies(a -> assertThat(a.getEmpleado()).as("check empleado").isEqualTo(expected.getEmpleado()))
            .satisfies(a -> assertThat(a.getTurnoLaboral()).as("check turnoLaboral").isEqualTo(expected.getTurnoLaboral()));
    }
}
