package com.mycompany.hospital.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EstadoDiagnosticoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEstadoDiagnosticoAllPropertiesEquals(EstadoDiagnostico expected, EstadoDiagnostico actual) {
        assertEstadoDiagnosticoAutoGeneratedPropertiesEquals(expected, actual);
        assertEstadoDiagnosticoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEstadoDiagnosticoAllUpdatablePropertiesEquals(EstadoDiagnostico expected, EstadoDiagnostico actual) {
        assertEstadoDiagnosticoUpdatableFieldsEquals(expected, actual);
        assertEstadoDiagnosticoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEstadoDiagnosticoAutoGeneratedPropertiesEquals(EstadoDiagnostico expected, EstadoDiagnostico actual) {
        assertThat(actual)
            .as("Verify EstadoDiagnostico auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEstadoDiagnosticoUpdatableFieldsEquals(EstadoDiagnostico expected, EstadoDiagnostico actual) {
        assertThat(actual)
            .as("Verify EstadoDiagnostico relevant properties")
            .satisfies(a -> assertThat(a.getCodigo()).as("check codigo").isEqualTo(expected.getCodigo()))
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()))
            .satisfies(a -> assertThat(a.getActivo()).as("check activo").isEqualTo(expected.getActivo()))
            .satisfies(a -> assertThat(a.getFechaAlta()).as("check fechaAlta").isEqualTo(expected.getFechaAlta()))
            .satisfies(a -> assertThat(a.getFechaBaja()).as("check fechaBaja").isEqualTo(expected.getFechaBaja()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEstadoDiagnosticoUpdatableRelationshipsEquals(EstadoDiagnostico expected, EstadoDiagnostico actual) {
        // empty method
    }
}
