package com.mycompany.hospital.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EstadoLaboralAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEstadoLaboralAllPropertiesEquals(EstadoLaboral expected, EstadoLaboral actual) {
        assertEstadoLaboralAutoGeneratedPropertiesEquals(expected, actual);
        assertEstadoLaboralAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEstadoLaboralAllUpdatablePropertiesEquals(EstadoLaboral expected, EstadoLaboral actual) {
        assertEstadoLaboralUpdatableFieldsEquals(expected, actual);
        assertEstadoLaboralUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEstadoLaboralAutoGeneratedPropertiesEquals(EstadoLaboral expected, EstadoLaboral actual) {
        assertThat(actual)
            .as("Verify EstadoLaboral auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEstadoLaboralUpdatableFieldsEquals(EstadoLaboral expected, EstadoLaboral actual) {
        assertThat(actual)
            .as("Verify EstadoLaboral relevant properties")
            .satisfies(a -> assertThat(a.getCodigo()).as("check codigo").isEqualTo(expected.getCodigo()))
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()))
            .satisfies(a -> assertThat(a.getFechaAlta()).as("check fechaAlta").isEqualTo(expected.getFechaAlta()))
            .satisfies(a -> assertThat(a.getFechaBaja()).as("check fechaBaja").isEqualTo(expected.getFechaBaja()))
            .satisfies(a -> assertThat(a.getActivo()).as("check activo").isEqualTo(expected.getActivo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEstadoLaboralUpdatableRelationshipsEquals(EstadoLaboral expected, EstadoLaboral actual) {
        // empty method
    }
}
