package com.mycompany.hospital.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FactorRhAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFactorRhAllPropertiesEquals(FactorRh expected, FactorRh actual) {
        assertFactorRhAutoGeneratedPropertiesEquals(expected, actual);
        assertFactorRhAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFactorRhAllUpdatablePropertiesEquals(FactorRh expected, FactorRh actual) {
        assertFactorRhUpdatableFieldsEquals(expected, actual);
        assertFactorRhUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFactorRhAutoGeneratedPropertiesEquals(FactorRh expected, FactorRh actual) {
        assertThat(actual)
            .as("Verify FactorRh auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFactorRhUpdatableFieldsEquals(FactorRh expected, FactorRh actual) {
        assertThat(actual)
            .as("Verify FactorRh relevant properties")
            .satisfies(a -> assertThat(a.getCodigo()).as("check codigo").isEqualTo(expected.getCodigo()))
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()))
            .satisfies(a -> assertThat(a.getActivo()).as("check activo").isEqualTo(expected.getActivo()))
            .satisfies(a -> assertThat(a.getFechaAlta()).as("check fechaAlta").isEqualTo(expected.getFechaAlta()))
            .satisfies(a -> assertThat(a.getFechaBaja()).as("check fechaBaja").isEqualTo(expected.getFechaBaja()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFactorRhUpdatableRelationshipsEquals(FactorRh expected, FactorRh actual) {
        // empty method
    }
}
