package com.mycompany.hospital.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HistoriaClinicaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoriaClinicaAllPropertiesEquals(HistoriaClinica expected, HistoriaClinica actual) {
        assertHistoriaClinicaAutoGeneratedPropertiesEquals(expected, actual);
        assertHistoriaClinicaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoriaClinicaAllUpdatablePropertiesEquals(HistoriaClinica expected, HistoriaClinica actual) {
        assertHistoriaClinicaUpdatableFieldsEquals(expected, actual);
        assertHistoriaClinicaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoriaClinicaAutoGeneratedPropertiesEquals(HistoriaClinica expected, HistoriaClinica actual) {
        assertThat(actual)
            .as("Verify HistoriaClinica auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoriaClinicaUpdatableFieldsEquals(HistoriaClinica expected, HistoriaClinica actual) {
        assertThat(actual)
            .as("Verify HistoriaClinica relevant properties")
            .satisfies(a -> assertThat(a.getNumero()).as("check numero").isEqualTo(expected.getNumero()))
            .satisfies(a -> assertThat(a.getFechaApertura()).as("check fechaApertura").isEqualTo(expected.getFechaApertura()))
            .satisfies(a ->
                assertThat(a.getFechaUltimaActualizacion())
                    .as("check fechaUltimaActualizacion")
                    .isEqualTo(expected.getFechaUltimaActualizacion())
            )
            .satisfies(a ->
                assertThat(a.getAntecedentesPersonales()).as("check antecedentesPersonales").isEqualTo(expected.getAntecedentesPersonales())
            )
            .satisfies(a ->
                assertThat(a.getAntecedentesFamiliares()).as("check antecedentesFamiliares").isEqualTo(expected.getAntecedentesFamiliares())
            )
            .satisfies(a ->
                assertThat(a.getEnfermedadesPrevias()).as("check enfermedadesPrevias").isEqualTo(expected.getEnfermedadesPrevias())
            )
            .satisfies(a -> assertThat(a.getCirugiasPrevias()).as("check cirugiasPrevias").isEqualTo(expected.getCirugiasPrevias()))
            .satisfies(a -> assertThat(a.getAlergias()).as("check alergias").isEqualTo(expected.getAlergias()))
            .satisfies(a ->
                assertThat(a.getMedicacionHabitual()).as("check medicacionHabitual").isEqualTo(expected.getMedicacionHabitual())
            )
            .satisfies(a -> assertThat(a.getHabitos()).as("check habitos").isEqualTo(expected.getHabitos()))
            .satisfies(a ->
                assertThat(a.getObservacionesGenerales()).as("check observacionesGenerales").isEqualTo(expected.getObservacionesGenerales())
            )
            .satisfies(a -> assertThat(a.getActiva()).as("check activa").isEqualTo(expected.getActiva()))
            .satisfies(a -> assertThat(a.getFechaCierre()).as("check fechaCierre").isEqualTo(expected.getFechaCierre()))
            .satisfies(a -> assertThat(a.getMotivoCierre()).as("check motivoCierre").isEqualTo(expected.getMotivoCierre()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoriaClinicaUpdatableRelationshipsEquals(HistoriaClinica expected, HistoriaClinica actual) {
        assertThat(actual)
            .as("Verify HistoriaClinica relationships")
            .satisfies(a -> assertThat(a.getPaciente()).as("check paciente").isEqualTo(expected.getPaciente()));
    }
}
