package com.mycompany.hospital.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MedicoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedicoAllPropertiesEquals(Medico expected, Medico actual) {
        assertMedicoAutoGeneratedPropertiesEquals(expected, actual);
        assertMedicoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedicoAllUpdatablePropertiesEquals(Medico expected, Medico actual) {
        assertMedicoUpdatableFieldsEquals(expected, actual);
        assertMedicoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedicoAutoGeneratedPropertiesEquals(Medico expected, Medico actual) {
        assertThat(actual)
            .as("Verify Medico auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedicoUpdatableFieldsEquals(Medico expected, Medico actual) {
        assertThat(actual)
            .as("Verify Medico relevant properties")
            .satisfies(a -> assertThat(a.getMatricula()).as("check matricula").isEqualTo(expected.getMatricula()))
            .satisfies(a ->
                assertThat(a.getFechaMatriculacion()).as("check fechaMatriculacion").isEqualTo(expected.getFechaMatriculacion())
            )
            .satisfies(a -> assertThat(a.getFirmaDigital()).as("check firmaDigital").isEqualTo(expected.getFirmaDigital()))
            .satisfies(a ->
                assertThat(a.getAtiendeConsultorio()).as("check atiendeConsultorio").isEqualTo(expected.getAtiendeConsultorio())
            )
            .satisfies(a -> assertThat(a.getActivo()).as("check activo").isEqualTo(expected.getActivo()))
            .satisfies(a -> assertThat(a.getFechaAlta()).as("check fechaAlta").isEqualTo(expected.getFechaAlta()))
            .satisfies(a -> assertThat(a.getFechaBaja()).as("check fechaBaja").isEqualTo(expected.getFechaBaja()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedicoUpdatableRelationshipsEquals(Medico expected, Medico actual) {
        assertThat(actual)
            .as("Verify Medico relationships")
            .satisfies(a -> assertThat(a.getEmpleado()).as("check empleado").isEqualTo(expected.getEmpleado()))
            .satisfies(a -> assertThat(a.getEspecialidad()).as("check especialidad").isEqualTo(expected.getEspecialidad()));
    }
}
