package com.mycompany.hospital.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ObraSocialAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertObraSocialAllPropertiesEquals(ObraSocial expected, ObraSocial actual) {
        assertObraSocialAutoGeneratedPropertiesEquals(expected, actual);
        assertObraSocialAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertObraSocialAllUpdatablePropertiesEquals(ObraSocial expected, ObraSocial actual) {
        assertObraSocialUpdatableFieldsEquals(expected, actual);
        assertObraSocialUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertObraSocialAutoGeneratedPropertiesEquals(ObraSocial expected, ObraSocial actual) {
        assertThat(actual)
            .as("Verify ObraSocial auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertObraSocialUpdatableFieldsEquals(ObraSocial expected, ObraSocial actual) {
        assertThat(actual)
            .as("Verify ObraSocial relevant properties")
            .satisfies(a -> assertThat(a.getCodigo()).as("check codigo").isEqualTo(expected.getCodigo()))
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getTelefono()).as("check telefono").isEqualTo(expected.getTelefono()))
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a -> assertThat(a.getDireccion()).as("check direccion").isEqualTo(expected.getDireccion()))
            .satisfies(a -> assertThat(a.getActivo()).as("check activo").isEqualTo(expected.getActivo()))
            .satisfies(a -> assertThat(a.getFechaAlta()).as("check fechaAlta").isEqualTo(expected.getFechaAlta()))
            .satisfies(a -> assertThat(a.getFechaBaja()).as("check fechaBaja").isEqualTo(expected.getFechaBaja()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertObraSocialUpdatableRelationshipsEquals(ObraSocial expected, ObraSocial actual) {
        // empty method
    }
}
