package com.mycompany.hospital.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PacienteAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPacienteAllPropertiesEquals(Paciente expected, Paciente actual) {
        assertPacienteAutoGeneratedPropertiesEquals(expected, actual);
        assertPacienteAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPacienteAllUpdatablePropertiesEquals(Paciente expected, Paciente actual) {
        assertPacienteUpdatableFieldsEquals(expected, actual);
        assertPacienteUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPacienteAutoGeneratedPropertiesEquals(Paciente expected, Paciente actual) {
        assertThat(actual)
            .as("Verify Paciente auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPacienteUpdatableFieldsEquals(Paciente expected, Paciente actual) {
        assertThat(actual)
            .as("Verify Paciente relevant properties")
            .satisfies(a ->
                assertThat(a.getNumeroHistoriaClinica()).as("check numeroHistoriaClinica").isEqualTo(expected.getNumeroHistoriaClinica())
            )
            .satisfies(a -> assertThat(a.getAlergiasGenerales()).as("check alergiasGenerales").isEqualTo(expected.getAlergiasGenerales()))
            .satisfies(a -> assertThat(a.getObservaciones()).as("check observaciones").isEqualTo(expected.getObservaciones()))
            .satisfies(a -> assertThat(a.getFechaAlta()).as("check fechaAlta").isEqualTo(expected.getFechaAlta()))
            .satisfies(a -> assertThat(a.getFechaBaja()).as("check fechaBaja").isEqualTo(expected.getFechaBaja()))
            .satisfies(a -> assertThat(a.getActivo()).as("check activo").isEqualTo(expected.getActivo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPacienteUpdatableRelationshipsEquals(Paciente expected, Paciente actual) {
        assertThat(actual)
            .as("Verify Paciente relationships")
            .satisfies(a -> assertThat(a.getPersona()).as("check persona").isEqualTo(expected.getPersona()))
            .satisfies(a -> assertThat(a.getObraSocial()).as("check obraSocial").isEqualTo(expected.getObraSocial()))
            .satisfies(a -> assertThat(a.getGrupoSanguineo()).as("check grupoSanguineo").isEqualTo(expected.getGrupoSanguineo()))
            .satisfies(a -> assertThat(a.getFactorRh()).as("check factorRh").isEqualTo(expected.getFactorRh()));
    }
}
