package com.mycompany.hospital.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PersonaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPersonaAllPropertiesEquals(Persona expected, Persona actual) {
        assertPersonaAutoGeneratedPropertiesEquals(expected, actual);
        assertPersonaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPersonaAllUpdatablePropertiesEquals(Persona expected, Persona actual) {
        assertPersonaUpdatableFieldsEquals(expected, actual);
        assertPersonaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPersonaAutoGeneratedPropertiesEquals(Persona expected, Persona actual) {
        assertThat(actual)
            .as("Verify Persona auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPersonaUpdatableFieldsEquals(Persona expected, Persona actual) {
        assertThat(actual)
            .as("Verify Persona relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getApellido()).as("check apellido").isEqualTo(expected.getApellido()))
            .satisfies(a -> assertThat(a.getNroDocumento()).as("check nroDocumento").isEqualTo(expected.getNroDocumento()))
            .satisfies(a -> assertThat(a.getFechaNacimiento()).as("check fechaNacimiento").isEqualTo(expected.getFechaNacimiento()))
            .satisfies(a -> assertThat(a.getTelefono()).as("check telefono").isEqualTo(expected.getTelefono()))
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a -> assertThat(a.getDireccion()).as("check direccion").isEqualTo(expected.getDireccion()))
            .satisfies(a -> assertThat(a.getActivo()).as("check activo").isEqualTo(expected.getActivo()))
            .satisfies(a -> assertThat(a.getFechaAlta()).as("check fechaAlta").isEqualTo(expected.getFechaAlta()))
            .satisfies(a -> assertThat(a.getFechaBaja()).as("check fechaBaja").isEqualTo(expected.getFechaBaja()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPersonaUpdatableRelationshipsEquals(Persona expected, Persona actual) {
        assertThat(actual)
            .as("Verify Persona relationships")
            .satisfies(a -> assertThat(a.getTipoDocumento()).as("check tipoDocumento").isEqualTo(expected.getTipoDocumento()))
            .satisfies(a -> assertThat(a.getSexo()).as("check sexo").isEqualTo(expected.getSexo()))
            .satisfies(a -> assertThat(a.getCiudad()).as("check ciudad").isEqualTo(expected.getCiudad()));
    }
}
