package com.mycompany.hospital.domain;

import static com.mycompany.hospital.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class SignosVitalesAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSignosVitalesAllPropertiesEquals(SignosVitales expected, SignosVitales actual) {
        assertSignosVitalesAutoGeneratedPropertiesEquals(expected, actual);
        assertSignosVitalesAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSignosVitalesAllUpdatablePropertiesEquals(SignosVitales expected, SignosVitales actual) {
        assertSignosVitalesUpdatableFieldsEquals(expected, actual);
        assertSignosVitalesUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSignosVitalesAutoGeneratedPropertiesEquals(SignosVitales expected, SignosVitales actual) {
        assertThat(actual)
            .as("Verify SignosVitales auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSignosVitalesUpdatableFieldsEquals(SignosVitales expected, SignosVitales actual) {
        assertThat(actual)
            .as("Verify SignosVitales relevant properties")
            .satisfies(a -> assertThat(a.getFechaHoraRegistro()).as("check fechaHoraRegistro").isEqualTo(expected.getFechaHoraRegistro()))
            .satisfies(a -> assertThat(a.getPeso()).as("check peso").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getPeso()))
            .satisfies(a -> assertThat(a.getTalla()).as("check talla").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getTalla()))
            .satisfies(a ->
                assertThat(a.getTemperatura())
                    .as("check temperatura")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getTemperatura())
            )
            .satisfies(a -> assertThat(a.getPresionArterial()).as("check presionArterial").isEqualTo(expected.getPresionArterial()))
            .satisfies(a ->
                assertThat(a.getFrecuenciaCardiaca()).as("check frecuenciaCardiaca").isEqualTo(expected.getFrecuenciaCardiaca())
            )
            .satisfies(a ->
                assertThat(a.getFrecuenciaRespiratoria()).as("check frecuenciaRespiratoria").isEqualTo(expected.getFrecuenciaRespiratoria())
            )
            .satisfies(a -> assertThat(a.getSaturacionOxigeno()).as("check saturacionOxigeno").isEqualTo(expected.getSaturacionOxigeno()))
            .satisfies(a -> assertThat(a.getObservaciones()).as("check observaciones").isEqualTo(expected.getObservaciones()))
            .satisfies(a -> assertThat(a.getActivo()).as("check activo").isEqualTo(expected.getActivo()))
            .satisfies(a -> assertThat(a.getFechaAlta()).as("check fechaAlta").isEqualTo(expected.getFechaAlta()))
            .satisfies(a -> assertThat(a.getFechaBaja()).as("check fechaBaja").isEqualTo(expected.getFechaBaja()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSignosVitalesUpdatableRelationshipsEquals(SignosVitales expected, SignosVitales actual) {
        assertThat(actual)
            .as("Verify SignosVitales relationships")
            .satisfies(a -> assertThat(a.getConsulta()).as("check consulta").isEqualTo(expected.getConsulta()));
    }
}
