package com.mycompany.hospital.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TipoDiagnosticoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoDiagnosticoAllPropertiesEquals(TipoDiagnostico expected, TipoDiagnostico actual) {
        assertTipoDiagnosticoAutoGeneratedPropertiesEquals(expected, actual);
        assertTipoDiagnosticoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoDiagnosticoAllUpdatablePropertiesEquals(TipoDiagnostico expected, TipoDiagnostico actual) {
        assertTipoDiagnosticoUpdatableFieldsEquals(expected, actual);
        assertTipoDiagnosticoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoDiagnosticoAutoGeneratedPropertiesEquals(TipoDiagnostico expected, TipoDiagnostico actual) {
        assertThat(actual)
            .as("Verify TipoDiagnostico auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoDiagnosticoUpdatableFieldsEquals(TipoDiagnostico expected, TipoDiagnostico actual) {
        assertThat(actual)
            .as("Verify TipoDiagnostico relevant properties")
            .satisfies(a -> assertThat(a.getCodigo()).as("check codigo").isEqualTo(expected.getCodigo()))
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()))
            .satisfies(a -> assertThat(a.getActivo()).as("check activo").isEqualTo(expected.getActivo()))
            .satisfies(a -> assertThat(a.getFechaAlta()).as("check fechaAlta").isEqualTo(expected.getFechaAlta()))
            .satisfies(a -> assertThat(a.getFechaBaja()).as("check fechaBaja").isEqualTo(expected.getFechaBaja()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoDiagnosticoUpdatableRelationshipsEquals(TipoDiagnostico expected, TipoDiagnostico actual) {
        // empty method
    }
}
