package com.mycompany.hospital.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TipoDocumentoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoDocumentoAllPropertiesEquals(TipoDocumento expected, TipoDocumento actual) {
        assertTipoDocumentoAutoGeneratedPropertiesEquals(expected, actual);
        assertTipoDocumentoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoDocumentoAllUpdatablePropertiesEquals(TipoDocumento expected, TipoDocumento actual) {
        assertTipoDocumentoUpdatableFieldsEquals(expected, actual);
        assertTipoDocumentoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoDocumentoAutoGeneratedPropertiesEquals(TipoDocumento expected, TipoDocumento actual) {
        assertThat(actual)
            .as("Verify TipoDocumento auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoDocumentoUpdatableFieldsEquals(TipoDocumento expected, TipoDocumento actual) {
        assertThat(actual)
            .as("Verify TipoDocumento relevant properties")
            .satisfies(a -> assertThat(a.getCodigo()).as("check codigo").isEqualTo(expected.getCodigo()))
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getSigla()).as("check sigla").isEqualTo(expected.getSigla()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()))
            .satisfies(a -> assertThat(a.getActivo()).as("check activo").isEqualTo(expected.getActivo()))
            .satisfies(a -> assertThat(a.getFechaAlta()).as("check fechaAlta").isEqualTo(expected.getFechaAlta()))
            .satisfies(a -> assertThat(a.getFechaBaja()).as("check fechaBaja").isEqualTo(expected.getFechaBaja()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoDocumentoUpdatableRelationshipsEquals(TipoDocumento expected, TipoDocumento actual) {
        // empty method
    }
}
