package com.mycompany.hospital.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TipoEmpleadoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoEmpleadoAllPropertiesEquals(TipoEmpleado expected, TipoEmpleado actual) {
        assertTipoEmpleadoAutoGeneratedPropertiesEquals(expected, actual);
        assertTipoEmpleadoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoEmpleadoAllUpdatablePropertiesEquals(TipoEmpleado expected, TipoEmpleado actual) {
        assertTipoEmpleadoUpdatableFieldsEquals(expected, actual);
        assertTipoEmpleadoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoEmpleadoAutoGeneratedPropertiesEquals(TipoEmpleado expected, TipoEmpleado actual) {
        assertThat(actual)
            .as("Verify TipoEmpleado auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoEmpleadoUpdatableFieldsEquals(TipoEmpleado expected, TipoEmpleado actual) {
        assertThat(actual)
            .as("Verify TipoEmpleado relevant properties")
            .satisfies(a -> assertThat(a.getCodigo()).as("check codigo").isEqualTo(expected.getCodigo()))
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()))
            .satisfies(a -> assertThat(a.getFechaAlta()).as("check fechaAlta").isEqualTo(expected.getFechaAlta()))
            .satisfies(a -> assertThat(a.getFechaBaja()).as("check fechaBaja").isEqualTo(expected.getFechaBaja()))
            .satisfies(a -> assertThat(a.getActivo()).as("check activo").isEqualTo(expected.getActivo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoEmpleadoUpdatableRelationshipsEquals(TipoEmpleado expected, TipoEmpleado actual) {
        // empty method
    }
}
