package com.mycompany.hospital.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TratamientoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTratamientoAllPropertiesEquals(Tratamiento expected, Tratamiento actual) {
        assertTratamientoAutoGeneratedPropertiesEquals(expected, actual);
        assertTratamientoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTratamientoAllUpdatablePropertiesEquals(Tratamiento expected, Tratamiento actual) {
        assertTratamientoUpdatableFieldsEquals(expected, actual);
        assertTratamientoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTratamientoAutoGeneratedPropertiesEquals(Tratamiento expected, Tratamiento actual) {
        assertThat(actual)
            .as("Verify Tratamiento auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTratamientoUpdatableFieldsEquals(Tratamiento expected, Tratamiento actual) {
        assertThat(actual)
            .as("Verify Tratamiento relevant properties")
            .satisfies(a -> assertThat(a.getCodigo()).as("check codigo").isEqualTo(expected.getCodigo()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()))
            .satisfies(a -> assertThat(a.getFechaInicio()).as("check fechaInicio").isEqualTo(expected.getFechaInicio()))
            .satisfies(a -> assertThat(a.getFechaFin()).as("check fechaFin").isEqualTo(expected.getFechaFin()))
            .satisfies(a -> assertThat(a.getObservaciones()).as("check observaciones").isEqualTo(expected.getObservaciones()))
            .satisfies(a ->
                assertThat(a.getFechaProximaRevision()).as("check fechaProximaRevision").isEqualTo(expected.getFechaProximaRevision())
            )
            .satisfies(a -> assertThat(a.getActivo()).as("check activo").isEqualTo(expected.getActivo()))
            .satisfies(a -> assertThat(a.getFechaAlta()).as("check fechaAlta").isEqualTo(expected.getFechaAlta()))
            .satisfies(a -> assertThat(a.getFechaBaja()).as("check fechaBaja").isEqualTo(expected.getFechaBaja()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTratamientoUpdatableRelationshipsEquals(Tratamiento expected, Tratamiento actual) {
        assertThat(actual)
            .as("Verify Tratamiento relationships")
            .satisfies(a -> assertThat(a.getDiagnostico()).as("check diagnostico").isEqualTo(expected.getDiagnostico()))
            .satisfies(a -> assertThat(a.getEstadoTratamiento()).as("check estadoTratamiento").isEqualTo(expected.getEstadoTratamiento()));
    }
}
