package com.mycompany.hospital.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TurnoLaboralAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTurnoLaboralAllPropertiesEquals(TurnoLaboral expected, TurnoLaboral actual) {
        assertTurnoLaboralAutoGeneratedPropertiesEquals(expected, actual);
        assertTurnoLaboralAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTurnoLaboralAllUpdatablePropertiesEquals(TurnoLaboral expected, TurnoLaboral actual) {
        assertTurnoLaboralUpdatableFieldsEquals(expected, actual);
        assertTurnoLaboralUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTurnoLaboralAutoGeneratedPropertiesEquals(TurnoLaboral expected, TurnoLaboral actual) {
        assertThat(actual)
            .as("Verify TurnoLaboral auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTurnoLaboralUpdatableFieldsEquals(TurnoLaboral expected, TurnoLaboral actual) {
        assertThat(actual)
            .as("Verify TurnoLaboral relevant properties")
            .satisfies(a -> assertThat(a.getCodigo()).as("check codigo").isEqualTo(expected.getCodigo()))
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getHoraInicio()).as("check horaInicio").isEqualTo(expected.getHoraInicio()))
            .satisfies(a -> assertThat(a.getHoraFin()).as("check horaFin").isEqualTo(expected.getHoraFin()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()))
            .satisfies(a -> assertThat(a.getActivo()).as("check activo").isEqualTo(expected.getActivo()))
            .satisfies(a -> assertThat(a.getFechaAlta()).as("check fechaAlta").isEqualTo(expected.getFechaAlta()))
            .satisfies(a -> assertThat(a.getFechaBaja()).as("check fechaBaja").isEqualTo(expected.getFechaBaja()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTurnoLaboralUpdatableRelationshipsEquals(TurnoLaboral expected, TurnoLaboral actual) {
        // empty method
    }
}
