package com.mycompany.hospital.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TurnoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTurnoAllPropertiesEquals(Turno expected, Turno actual) {
        assertTurnoAutoGeneratedPropertiesEquals(expected, actual);
        assertTurnoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTurnoAllUpdatablePropertiesEquals(Turno expected, Turno actual) {
        assertTurnoUpdatableFieldsEquals(expected, actual);
        assertTurnoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTurnoAutoGeneratedPropertiesEquals(Turno expected, Turno actual) {
        assertThat(actual)
            .as("Verify Turno auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTurnoUpdatableFieldsEquals(Turno expected, Turno actual) {
        assertThat(actual)
            .as("Verify Turno relevant properties")
            .satisfies(a -> assertThat(a.getCodigo()).as("check codigo").isEqualTo(expected.getCodigo()))
            .satisfies(a -> assertThat(a.getFechaHora()).as("check fechaHora").isEqualTo(expected.getFechaHora()))
            .satisfies(a -> assertThat(a.getDuracionMinutos()).as("check duracionMinutos").isEqualTo(expected.getDuracionMinutos()))
            .satisfies(a -> assertThat(a.getMotivoConsulta()).as("check motivoConsulta").isEqualTo(expected.getMotivoConsulta()))
            .satisfies(a -> assertThat(a.getObservaciones()).as("check observaciones").isEqualTo(expected.getObservaciones()))
            .satisfies(a -> assertThat(a.getFechaCreacion()).as("check fechaCreacion").isEqualTo(expected.getFechaCreacion()))
            .satisfies(a -> assertThat(a.getActivo()).as("check activo").isEqualTo(expected.getActivo()))
            .satisfies(a -> assertThat(a.getFechaAlta()).as("check fechaAlta").isEqualTo(expected.getFechaAlta()))
            .satisfies(a -> assertThat(a.getFechaBaja()).as("check fechaBaja").isEqualTo(expected.getFechaBaja()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTurnoUpdatableRelationshipsEquals(Turno expected, Turno actual) {
        assertThat(actual)
            .as("Verify Turno relationships")
            .satisfies(a -> assertThat(a.getPaciente()).as("check paciente").isEqualTo(expected.getPaciente()))
            .satisfies(a -> assertThat(a.getMedico()).as("check medico").isEqualTo(expected.getMedico()))
            .satisfies(a -> assertThat(a.getEspecialidad()).as("check especialidad").isEqualTo(expected.getEspecialidad()))
            .satisfies(a -> assertThat(a.getEstadoTurno()).as("check estadoTurno").isEqualTo(expected.getEstadoTurno()))
            .satisfies(a -> assertThat(a.getCanalSolicitud()).as("check canalSolicitud").isEqualTo(expected.getCanalSolicitud()));
    }
}
